version: '3'

services:
    php:
        build:
            context: ./docker/php
        depends_on:
            - db
        volumes:
            - .:/var/www/rapier
            - ./var/logs:/var/log/rapier
        expose:
            - "9000"
        environment:
            SYMFONY_ENV: dev
    nginx:
        build: ./docker/nginx
        depends_on:
            - php
        volumes:
            - .:/var/www/rapier
            - ./var/logs:/var/log/nginx
        ports:
            - "80:80"
    db:
        image: postgres:latest
        volumes:
            - ./backups:/backups
            - db:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: rapier
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
    mailcatcher:
        image: schickling/mailcatcher
        ports:
            - "1080:1080"
            - "1025:1025"

volumes:
    db: