imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    translator: false
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

doctrine:
    dbal:
        driver:       pdo_pgsql
        host:         "%env(TEST_DATABASE_HOST)%"
        port:         "5432"
        dbname:       "%env(TEST_DATABASE_NAME)%"
        user:         "%env(TEST_DATABASE_USER)%"
        password:     ~
        charset:      UTF8

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true