imports:
    -
        resource: parameters.yml
    -
        resource: security.yml
    -
        resource: services.yml
parameters:
    locale: en
framework:
    translator:
        fallbacks:
            - '%locale%'
    default_locale: en
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: null
    form: null
    csrf_protection: null
    validation:
        enable_annotations: true
    templating:
        engines:
            - twig
    trusted_hosts: null
    trusted_proxies: null
    session:
        handler_id: session.handler.native_file
        save_path: '%kernel.root_dir%/../var/sessions/%kernel.environment%'
    fragments: null
    http_method_override: true
    assets: null
    workflows:
        EventLifecycle:
            type: state_machine
            supports: AppBundle\Entity\Event
            marking_store:
                type: single_state
                argument: currentPlace
            places:
                - TLCStartEvent
                - CreateAnEvent
                - StartAnEvent
                - StopAnEvent
                - CloseAnEvent
                - IsEventFinishedGateway
                - TLCEndEvent
            transitions:
                EventNotFinishedFlow:
                    from: IsEventFinishedGateway
                    to: StartAnEvent
                EventIsFinishedFlow:
                    from: IsEventFinishedGateway
                    to: CloseAnEvent
                f0:
                    from: TLCStartEvent
                    to: CreateAnEvent
                f1:
                    from: CreateAnEvent
                    to: StartAnEvent
                f2:
                    from: StartAnEvent
                    to: StopAnEvent
                f3:
                    from: StopAnEvent
                    to: IsEventFinishedGateway
                f4:
                    from: CloseAnEvent
                    to: TLCEndEvent
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
doctrine:
    dbal:
        driver: pdo_pgsql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    port: '%mailer_port%'
    encryption: '%mailer_encryption%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool:
        type: memory
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    service:
        mailer: fos_user.mailer.twig_swift
    registration:
        confirmation:
            enabled: true
            template: '@FOSUser/Registration/email.txt.twig'
    from_email:
        address: '%mailer_user%'
        sender_name: '%mailer_send_as%'
jms_serializer:
    metadata:
        directories:
            DTO_API:
                namespace_prefix: AppBundle\Model\DTO\API
                path: '@AppBundle/Resources/serializer/api'
fos_rest:
    view:
        view_response_listener:
            enabled: true
            force: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: php
        formats:
            json: true
    serializer:
        serialize_null: true
    service:
        serializer: fos_rest.serializer.jms
    body_listener:
        decoders:
            json: fos_rest.decoder.json
    access_denied_listener:
        enabled: true
    exception: true
    routing_loader:
        default_format: json
    format_listener:
        rules:
            -
                path: ^/api
                priorities:
                    - json
                fallback_format: json
                prefer_extension: true
    zone:
        -
            path: '^\/api\/.*'
nelmio_api_doc:
    documentation:
        info:
            title: 'Rapier Application'
            description: 'This is api!'
            version: 1.0.0
        securityDefinitions:
            ApiKey:
                type: basic
                description: 'Basic Auth'
                in: header
        security:
            -
                ApiKey:
                    - '%secret%'
    areas:
        path_patterns:
            - '^/api(?!/doc$)'
phpmentors_workflower:
    serializer_service: phpmentors_workflower.base64_php_workflow_serializer
    workflow_contexts:
        app:
            definition_dir: '%kernel.root_dir%/../src/AppBundle/Resources/config/workflower'
